export { default as HeroSection } from './hero.svelte';
export { default as PainPoints } from './pain-points.svelte';
export { default as Solutions } from './solutions.svelte';
export { default as PhotoSharing } from './photo-sharing.svelte';
export { default as Benefits } from './benefits.svelte';
export { default as Testimonials } from './testimonials.svelte';
export { default as LastCta } from './last-cta.svelte';
export { default as Faq } from './faq.svelte';
export { default as Pricing } from './pricing.svelte';
